[WIP] Add cgmes-boundary-server
gridsuite/gateway pull request #23
Opened 2021-04-15 12:01 UTC by FranckLecuyer

2021-04-20 11:59 UTC, ChamseddineBhd requested changes

2021-04-21 09:27 UTC, JacquesBorsenberger approved these changes

2021-04-21 09:43 UTC, FranckLecuyer commented on pom.xml
> +        <gridsuite-dependencies.version>5</gridsuite-dependencies.version>
it is done in PR : https://github.com/gridsuite/gateway/pull/24, but this PR in not merged yet

2021-04-22 09:40 UTC, FranckLecuyer commented on pom.xml
> +        <gridsuite-dependencies.version>5</gridsuite-dependencies.version>
Done

2021-04-22 09:42 UTC, ChamseddineBhd approved these changes

2021-04-22 09:43 UTC, ChamseddineBhd approved these changes

2021-04-22 09:43 UTC, merged